server:
  port: 9003
spring:
  application:
    name: hp_sdn
  main:
    banner-mode: off
    log-startup-info: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: rajatmeena985@gmail.com
    password: 11121993
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hp_sdn?serverTimezone=UTC
    username: root
    password: Supernayap@ssw0rd
  jpa:
    hibernate.ddl-auto: none
    database: mysql

senderEmail: rajatmeena985@gmail.com
senderName: Rajat Meena
adminEmail: rajatmeena985@gmail.com
adminName: Sandeepan
receiverEmails: rajat8527@gmfsfsfddsfail.com,rajsfdsdfsdfsdfsdfsdfat8528@gmafdfsfil.com
receiverNames: Marta,David